### ISSUE TITLE
Extension does not work with PostGIS 2.0

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-spatial#5]
Because geoalchemy does not support it. See [1]. Apparently [geoalchemy2](http://geoalchemy-2.readthedocs.org/en/latest/) is the way to go.

[1] https://github.com/geoalchemy/geoalchemy/issues/22

**Comment by davidread** [comment]
Just to elaborate on @florianm 's comment, for other googlers to here, I believe he's describing the incompatibility between SQLAlchemy 0.9.x and GeoAlchemy. That results in the error:

    AttributeError: type object 'ColumnProperty' has no attribute 'ColumnComparator'

And it can be solved by upgrading to GeoAlchemy2 or chokoswitch's fork of GeoAlchemy, as described by Florian.
